firstapp/urls.py
from django.urls import path
from . import views

app_name = 'firstapp'
urlpatterns = [
    path('',views.main),
    path('one/',views.one, name="page_one"),
    path('two/',views.two, name="page_two"),
    path('three/',views.three, name="page_three"), 
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('first/',include('firstapp.urls')),
    path('second/',include('secondapp.urls')),
]

secondapp/urls.py
from django.urls import path
from . import views

# app_name = 'secondapp'
urlpatterns = [
    path('one/', views.one, name="page_one"),
]

firstapp/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    view_count = models.IntegerField(default = 0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

secondapp/models.py
from django.db import models

# Create your models here.

firstapp/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'firstapp/main.html')

def one(request):
    return render(request, 'firstapp/one.html')

def two(request):
    return render(request, 'firstapp/two.html')

def three(request):
    return render(request, 'firstapp/three.html')

secondapp/views.py
from django.shortcuts import render

# Create your views here.
def one(request):
    return render(request, 'secondapp/one.html')

firstapp/templates/firstapp/main.html
<h1>2020 Dongguk Likelion</h1>
<a href="{% url 'firstapp:page_one' %}">one</a>
<a href="{% url 'firstapp:page_two' %}">two</a>
<a href="{% url 'firstapp:page_three' %}">three</a>

firstapp/templates/firstapp/one.html
<h1>1</h1>

firstapp/templates/firstapp/three.html
<h1>3</h1>

firstapp/templates/firstapp/two.html
<h1>2</h1>

secondapp/templates/secondapp/one.html
<h1>secondapp 1</h1>